language: cpp

matrix:
    include:
        - compiler: clang
          os: osx
        - compiler: clang
          os: ios
          osx_image: xcode8
        - compiler: clang
          os: linux

script:
    - "scripts/build_${TRAVIS_OS_NAME}.sh"

notifications:
    email: false

