language: cpp

matrix:
    include:
        - compiler: clang
          os: osx
#    include:
#        - compiler: clang
#          os: ios
        - compiler: clang
          os: linux

script:
    - "scripts/build_${TRAVIS_OS_NAME}.sh"

notifications:
    email: false

