language: cpp

matrix:
    include:
        - compiler: clang
          os: osx
          env: arch=x86_64

        - compiler: clang
          os: osx
          env: arch=arm

        - compiler: clang
          os: linux

script:
    - "scripts/build_${TRAVIS_OS_NAME}.sh"

notifications:
    email: false

